### ISSUE TITLE
Install via spack fails on Kubuntu 22.04

### ISSUE THREAD

**Issue by fhindenlang** [trixi-framework/HOHQMesh#120]
I followed the steps from the readme:
```
git clone https://github.com/spack/spack.git ~/spack
source ~/spack/share/spack/setup-env.sh
spack install hohqmesh@main
```
the last step throws the following errror:
```
==> Error: failed to concretize `hohqmesh@main` for the following reasons:
     1. Cannot satisfy 'hohqmesh@main'
     2. Cannot satisfy 'hohqmesh@main'
        required because hohqmesh@main requested explicitly 
```

**Comment by fluidnumerics-joe** [comment]
What happens when you try to install without the `@main` version specifier. I'll need to double check but last I recall, we don't have a branch version in Spack for HOHQMesh, only tagged releases.

**Comment by fluidnumerics-joe** [comment]
What does your `compilers.yaml` file look like. Usually this is under `$HOME/.spack/`

**Comment by sloede** [comment]
@fluidnumerics-joe I assume you mean @fhindenlang?

For reference, here are mine:
<details>
<summary>Ubuntu 20.04</summary>

```yml
compilers:
- compiler:
    spec: clang@=17.0.6
    paths:
      cc: /usr/bin/clang-17
      cxx: /usr/bin/clang++-17
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=8.4.0
    paths:
      cc: /usr/bin/gcc-8
      cxx: /usr/bin/g++-8
      f77: /usr/bin/gfortran-8
      fc: /usr/bin/gfortran-8
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=9.4.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=10.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
</details>

<details>
<summary>Ubuntu 24.04</summary>

```yml
compilers:
- compiler:
    spec: gcc@=12.3.0
    paths:
      cc: /usr/bin/gcc-12
      cxx: /usr/bin/g++-12
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu24.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=13.2.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu24.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
</details>
</details>
